# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'marketpage_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets

from src.components.Books.Books import Books
from src.components.Navigation.Navigation import Navigation


class Ui_Form(object):
    def setupUi(self, Form, book_func):
        Form.setObjectName("Form")
        Form.resize(1280, 760)
        Form.setStyleSheet("")
        Form.setGeometry(QtCore.QRect(0, 70, 1280, 760))
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 760))
        self.frame.setStyleSheet("background: #e9e9e9")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.active_category = [0]
        self.nav_widget = Navigation(self.frame, self.active_category)
        self.nav_widget.setGeometry(QtCore.QRect(40, 50, 290, 660))
        self.nav_widget.setObjectName("nav_widget")
        self.scrollArea = Books(self.nav_widget.categories[0][0], book_func, parent=self.frame)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))