# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookpage_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.components.Annotation.Annotation import Annotation
from src.components.BookShort.BookShort import BookShort
from src.components.Reviews.Reviews import Reviews


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 760)
        Form.setGeometry(QtCore.QRect(0, 70, 1280, 760))
        self.book_widget = BookShort("a", "a", "a", "a", "a", 0, parent=Form)
        self.book_widget.setGeometry(QtCore.QRect(40, 40, 590, 220))
        self.book_widget.setObjectName("book_widget")
        self.annotation_widget = Annotation(Form)
        self.annotation_widget.setGeometry(QtCore.QRect(650, 40, 590, 220))
        self.annotation_widget.setObjectName("annotation_widget")
        self.reviews_widget = Reviews(Form)
        self.reviews_widget.setGeometry(QtCore.QRect(40, 290, 1200, 440))
        self.reviews_widget.setObjectName("reviews_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
