# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigation_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(290, 660)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 290, 660))
        self.frame.setStyleSheet("border-radius: 8px;\n"
"background: #ffffff")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.active_font = QtGui.QFont()
        self.active_font.setPointSize(12)
        self.active_font.setBold(True)
        self.active_font.setWeight(70)
        self.order_font = QtGui.QFont()
        self.order_font.setPointSize(12)
        self.order_font.setBold(True)
        self.order_font.setWeight(40)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
