# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartpage_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore

from src.components.Bill.Bill import Bill
from src.components.CartBooks.CartBooks import CartBooks


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 760)
        Form.setGeometry(QtCore.QRect(0, 70, 1280, 800))
        self.bill_widget = Bill(Form)
        self.bill_widget.setGeometry(QtCore.QRect(20, 50, 370, 500))
        self.bill_widget.setObjectName("bill_widget")
        self.books_widget = CartBooks(Form)
        self.books_widget.setObjectName("books_widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

