# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'header_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 70)
        Form.setStyleSheet("background: #000000")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 70))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cartBtn = QtWidgets.QPushButton(self.frame)
        self.cartBtn.setGeometry(QtCore.QRect(1200, 20, 32, 32))
        self.cartBtn.setStyleSheet("backgroud: black")
        self.cartBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/components/Header/icon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cartBtn.setIcon(icon)
        self.cartBtn.setIconSize(QtCore.QSize(32, 32))
        self.cartBtn.setObjectName("cartBtn")
        self.shopBtn = QtWidgets.QPushButton(self.frame)
        self.shopBtn.setGeometry(QtCore.QRect(40, 20, 120, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.shopBtn.setFont(font)
        self.shopBtn.setStyleSheet("color: #ffffff")
        self.shopBtn.setObjectName("shopBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.shopBtn.setText(_translate("Form", "Магазин"))
