# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_style.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.components.Star.star import Star


class Ui_Form(object):
    def setupUi(self, Form, title, authors, genre, price, rate, number):
        Form.setGeometry(QtCore.QRect(0, 0, 870, 220))
        Form.setMinimumSize(870, 200)
        Form.setMaximumSize(870, 200)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Form.setFont(font)
        Form.setTabletTracking(False)
        Form.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background: #ffffff;\n"
                           "border-radius: 8px")
        Form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Form.setFrameShadow(QtWidgets.QFrame.Raised)
        Form.setObjectName("frame")
        self.book_btn = QtWidgets.QPushButton(Form)
        self.book_btn.setGeometry(QtCore.QRect(20, 16, 830, 27))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.book_btn.setFont(font)
        self.book_btn.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.book_btn.setStyleSheet("text-align: left;\n"
                                    "background: #ffffff")
        self.book_btn.setObjectName("book_btn")
        self.author = QtWidgets.QLabel(Form)
        self.author.setGeometry(QtCore.QRect(20, 65, 600, 22))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.author.setFont(font)
        self.author.setStyleSheet("font-style: normal;\n"
                                  "font-weight: 400;\n"
                                  "font-size: 16px;\n"
                                  "color: rgba(0, 0, 0, 0.5);")
        self.author.setObjectName("author")
        self.genre = QtWidgets.QLabel(Form)
        self.genre.setGeometry(QtCore.QRect(20, 95, 600, 22))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.genre.setFont(font)
        self.genre.setStyleSheet("font-style: normal;\n"
                                 "font-weight: 400;\n"
                                 "font-size: 16px;\n"
                                 "color: rgba(0, 0, 0, 0.5);")
        self.genre.setObjectName("genre")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(20, 125, 120, 16))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 120, 16))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.stars = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.stars.setContentsMargins(0, 0, 0, 0)
        self.stars.setObjectName("starts")
        for i in range(rate):
            self.stars.addWidget(Star(Form, star_type="fill"))
        for i in range(5 - rate):
            self.stars.addWidget(Star(Form))
        self.price = QtWidgets.QLabel(Form)
        self.price.setGeometry(QtCore.QRect(20, 163, 200, 33))
        self.price.setStyleSheet("font-style: normal;\n"
                                 "font-weight: 700;\n"
                                 "font-size: 24px;")
        self.price.setObjectName("price")
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.increment = QtWidgets.QPushButton(Form)
        self.increment.setGeometry(QtCore.QRect(760, 90, 40, 40))
        self.increment.setText("+")
        self.increment.setFont(font)
        self.increment.setStyleSheet("background: #000000; color: white;")
        self.increment.setObjectName("increment")
        self.decrement = QtWidgets.QPushButton(Form)
        self.decrement.setGeometry(QtCore.QRect(660, 90, 40, 40))
        self.decrement.setText("-")
        self.decrement.setFont(font)
        self.decrement.setStyleSheet("background: #000000; color: white;")
        self.decrement.setObjectName("decrement")
        self.numberLabel = QtWidgets.QLabel(Form)
        self.numberLabel.setGeometry(QtCore.QRect(710, 90, 40, 40))
        self.numberLabel.setText(str(number))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.numberLabel.setFont(font)
        self.numberLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.numberLabel.setObjectName("numberLabel")

        self.retranslateUi(Form, title, authors, genre, price)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form, title, authors, genre, price):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.book_btn.setText(_translate("Form", title))
        self.author.setText(_translate("Form", ", ".join(authors)))
        self.genre.setText(_translate("Form", genre))
        self.price.setText(_translate("Form", f"{price}P"))
